# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: "Stremio Streaming Service"
description: "Stremio streaming server (server.js) for local network streaming. Offload the streaming backend from your TV to your Home Assistant machine."
version: "0.1.0"
slug: "stremio-server"
url: "https://github.com/timojokinen/hassio-stremio-server"
arch:
  - amd64
  - aarch64
init: false
homeassistant_api: false
host_network: true
watchdog: "http://[HOST]:11470"
ingress: false
startup: services
map:
  - config:rw
  - share:rw
options:
  server_url: "https://dl.strem.io/server/v4.20.16/desktop/server.js"
schema:
  server_url: url
panel_icon: "mdi:filmstrip"
